import Header from './_components/Header/Header';
import ToasterContext from './_context/ToasterContext';
import './globals.css';

export const metadata = {
  title: 'Yardstick - Assignment',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-gray-200">
        <ToasterContext />
        <Header />
        {children}
      </body>
    </html>
  );
}
